config/routes.rb
Rails.application.routes.draw do

  resources :answers

  resources :questions

  root 'home#index'
  
  get '/about' => 'home#about'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	include HasGravatar
	belongs_to :question

end

app/models/concerns/has_gravatar.rb
module	HasGravatar
	def gravatar
		"http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
	end
end

app/models/question.rb
class Question < ActiveRecord::Base
	include HasGravatar
	has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		question = Question.find(params[:answer][:question_id])
		answer = question.answers.create(answer_params)

		MainMailer.notify_question_author(answer).deliver

		session[:current_user_email] = answer_params[:email]
		redirect_to question
	end

	private

	def answer_params
		params.require(:answer).permit(:email, :body)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@questions = Question.order(created_at: :desc).all
  end

  def about
  end

  def temp
  	redirect_to root_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
  	@question = Question.find(params[:id])
    @answers = @question.answers.order(created_at: :desc)
  end

  def create
    Question.create(question_params)
    session[:current_user_email] = question_params[:email]
    redirect_to root_path
  end

  private

  def question_params
    params.require(:question).permit(:email, :body)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user_email
		session[:current_user_email]
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_nav.html.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">WebSiteName</a>
		</div>
		<div>
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">Home</a></li>
				<li><a href="#">Page 1</a></li>
				<li><a href="#">Page 2</a></li> 
				<li><a href="#">Page 3</a></li>
			</ul>
			<form class="navbar-form navbar-right">
				<a ><%= current_user_email %></a>
				<button class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">Ask Question</button>
			</form>
		</div>
	</div>
</nav>	

app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="myAnswer">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Answer Question</h4>
			</div>
			<%= form_for :answer, url: '/answers' do %>
			<input type="hidden" name="answer[question_id]" value="<%= @question.id %>">
				<div class="modal-body">
					<div class="form-group">
						<label for="exampleInputEmail1">Email address</label>
						<input required type="email" value="<%= current_user_email %>" name="answer[email]" class="form-control" id="exampleInputEmail1" placeholder="Email">
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">Answer</label>
						<textarea type="text" name="answer[body]" class="form-control" id="Answer" placeholder="Your Answer"></textarea>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save changes</button>
				</div>
			<% end %>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/home/_new_question_form.html.erb
<div class="modal fade" id="myModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Modal title</h4>
			</div>
			<%= form_for :question, url: '/questions' do %>
				<div class="modal-body">
					<div class="form-group">
						<label for="exampleInputEmail1">Email address</label>
						<input required type="email" value="<%= current_user_email %>" name="question[email]" class="form-control" id="exampleInputEmail1" placeholder="Email">
					</div>
					<div class="form-group">
						<label for="Question">Question</label>
						<textarea name="question[body]" type="text" class="form-control" id="Question" placeholder="Your Question"></textarea>
					</div>

				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save changes</button>
				</div>
			<% end %>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/home/about.html.erb
<h1>About Teddy Koufos</h1>

app/views/home/index.html.erb
<h1>Teddy's Tables</h1>
<div class="bs-example" data-example-id="default-media">
	<% @questions.each do |q| %>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="media-object" style="width: 64px; height: 64px;" src="<%= q.gravatar %>" data-holder-rendered="true">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= q.email %></h4>

        <p><%= time_ago_in_words q.created_at %> ago</p>

        <p><%= q.body %></p>
		
        <a href="<%= question_path(q) %>" class="btn btn-success btn-sm">View Answers</a>
      </div>
    </div>
    <% end %>
    <% if @questions.empty? %>
      <div class="alert alert-info">No Questions here currently.</div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TeddysTables</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<%= csrf_meta_tags %>
</head>
<body>
	
	<%= render 'home/nav' %>

	<div class="container">
		
	
		<%= yield %>

		
	</div>

	<%= render 'home/new_question_form' %>
</body>
</html>

app/views/questions/show.html.erb
<div class="lead well">
  <div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" style="width: 64px; height: 64px;" src="<%= @question.gravatar %>" data-holder-rendered="true">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= @question.email %></h4>
    <p><%= @question.body %></p>
  </div>
</div>
</div>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <button type="button" data-toggle="modal" data-target="#myAnswer" class="btn btn-success">Submit Answer</button>
    <% @answers.each do |answer| %>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="media-object" style="width: 64px; height: 64px;" src="<%= answer.gravatar %>" data-holder-rendered="true">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= answer.email %> answered:</h4>
        <p><%= time_ago_in_words answer.created_at %> ago</p>
        <p><%= answer.body %></p>
      </div>
    </div>
  <% end %>
  <% if @answers.empty? %>
      <br>
      <br>
      <div class="alert alert-info">No Answers here currently.</div>
    <% end %>
</div>
  <%= render 'home/new_answer_form' %>

</div>